#ifndef INTERFAZ_TAREA1_GLOBAL_H
#define INTERFAZ_TAREA1_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERFAZ_TAREA1_LIBRARY)
#  define INTERFAZ_TAREA1_EXPORT Q_DECL_EXPORT
#else
#  define INTERFAZ_TAREA1_EXPORT Q_DECL_IMPORT
#endif

#endif // INTERFAZ_TAREA1_GLOBAL_H
